export type ServiceSlug = "web-tasarim" | "seo" | "mobil-uygulama" | "e-ticaret";
export type Service = { slug: ServiceSlug; eyebrow: string; title: string; shortTitle: string; promise: string; summary: string; priceSignal: string; audience: readonly string[]; deliverables: readonly string[]; projectSlugs: readonly string[] };

export const services = [
  { slug: "web-tasarim", eyebrow: "Web sitesi ve blog", shortTitle: "Web Tasarım", title: "Hızlı açılan, kolay okunan ve markanızı doğru anlatan web siteleri.", promise: "İlk ziyaretten iletişime kadar gereksiz sürtünmeyi azaltan bir web deneyimi.", summary: "İçerik hiyerarşisi, arayüz tasarımı ve geliştirme aynı elde ilerler; ortaya tutarlı ve yönetilebilir bir site çıkar.", priceSignal: "7.000 TL’den başlayan hizmet bedeli", audience: ["Yeni bir web sitesiyle yayına çıkacak markalar", "Eski sitesini sadeleştirmek ve hızlandırmak isteyen işletmeler", "İçeriğini düzenli yayınlayan uzmanlar ve ekipler"], deliverables: ["İçerik ve sayfa yapısı", "Responsive arayüz tasarımı", "Geliştirme ve temel teknik SEO", "Erişilebilirlik ve yayın öncesi kalite kontrolü"], projectSlugs: ["vela-windsurfing", "cemwebstudio"] },
  { slug: "seo", eyebrow: "SEO", shortTitle: "SEO", title: "Arama motorları için değil, arayan insan için bulunabilir olun.", promise: "Teknik sorunları, içerik fırsatlarını ve öncelikleri anlaşılır bir yol haritasına dönüştürün.", summary: "Audit, teknik SEO, içerik ve anahtar kelime çalışmaları ihtiyaca göre tek seferlik veya aylık kapsamlanır.", priceSignal: "Kapsama göre teklif", audience: ["Organik görünürlüğünü yeni kuran siteler", "Teknik sorunları büyümeyi sınırlayan ekipler", "İçerik üretimini arama niyetiyle buluşturmak isteyen markalar"], deliverables: ["Teknik ve içerik audit’i", "Önceliklendirilmiş aksiyon listesi", "Anahtar kelime ve içerik yönü", "İhtiyaca göre aylık takip seçeneği"], projectSlugs: [] },
  { slug: "mobil-uygulama", eyebrow: "Mobil uygulama", shortTitle: "Mobil Uygulama", title: "Fikrinizi, kullanıcıların anlayıp benimseyeceği bir mobil ürüne dönüştürün.", promise: "Keşiften prototipe ve MVP’ye kadar kararları görünür kılan ürün süreci.", summary: "Platform ve teknoloji seçimi, hedef kullanıcı, kapsam ve sürdürülebilirlik gereksinimleri birlikte değerlendirildikten sonra yapılır.", priceSignal: "Kapsama göre teklif", audience: ["Yeni bir mobil ürün fikrini doğrulayan girişimler", "Mevcut hizmetini mobile taşımak isteyen markalar", "Karmaşık akışları sadeleştirmek isteyen ürün ekipleri"], deliverables: ["Keşif ve gereksinim çerçevesi", "UX/UI ve etkileşim tasarımı", "Tıklanabilir prototip", "MVP ve geliştirme kapsamı"], projectSlugs: ["drn-servis-paneli"] },
  { slug: "e-ticaret", eyebrow: "E-ticaret", shortTitle: "E-ticaret", title: "Ürünleri öne çıkaran, satın alma yolunu kısaltan e-ticaret deneyimleri.", promise: "Mağaza vitrini, ürün keşfi ve checkout aynı performans hedefi etrafında tasarlanır.", summary: "Kapsam; ürün sayısı, ödeme, kargo ve gerekli entegrasyonlar brief sonrasında netleşir.", priceSignal: "15.000 TL’den başlayan hizmet bedeli", audience: ["İlk kez çevrimiçi satışa başlayacak işletmeler", "Hazır mağazasını markasına göre yenilemek isteyenler", "Ürün keşfini ve alışveriş akışını iyileştirmek isteyen ekipler"], deliverables: ["Mağaza bilgi mimarisi", "Responsive vitrin ve ürün deneyimi", "Sepet ve checkout akışı", "Brief’e göre gerekli entegrasyon çerçevesi"], projectSlugs: ["aysaworks", "bluekim"] },
] as const satisfies readonly Service[];

export const getService = (slug: ServiceSlug) => services.find((service) => service.slug === slug);
